import 'package:flutter/material.dart';
import 'aster_colors.dart';

/// Aster Material 3 Color Schemes for Light and Dark themes.
abstract class AsterColorScheme {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: AsterColors.lightPrimary,
    onPrimary: AsterColors.lightOnPrimary,
    primaryContainer: AsterColors.lightPrimaryContainer,
    onPrimaryContainer: AsterColors.lightOnPrimaryContainer,
    secondary: AsterColors.lightSecondary,
    onSecondary: AsterColors.lightOnSecondary,
    secondaryContainer: AsterColors.lightSecondaryContainer,
    onSecondaryContainer: AsterColors.lightOnSecondaryContainer,
    tertiary: AsterColors.lightTertiary,
    onTertiary: AsterColors.lightOnTertiary,
    tertiaryContainer: AsterColors.lightTertiaryContainer,
    onTertiaryContainer: AsterColors.lightOnTertiaryContainer,
    error: AsterColors.lightError,
    onError: AsterColors.lightOnError,
    errorContainer: AsterColors.lightErrorContainer,
    onErrorContainer: AsterColors.lightOnErrorContainer,
    surface: AsterColors.lightSurface,
    onSurface: AsterColors.lightOnSurface,
    onSurfaceVariant: AsterColors.lightOnSurfaceVariant,
    outline: AsterColors.lightOutline,
    outlineVariant: AsterColors.lightOutlineVariant,
    shadow: Color(0xFF000000),
    inverseSurface: AsterColors.lightInverseSurface,
    onInverseSurface: AsterColors.lightInverseOnSurface,
    inversePrimary: AsterColors.lightInversePrimary,
    surfaceTint: AsterColors.lightSurfaceTint,
    surfaceDim: AsterColors.lightSurfaceDim,
    surfaceBright: AsterColors.lightSurfaceBright,
    surfaceContainerLowest: AsterColors.lightSurfaceContainerLowest,
    surfaceContainerLow: AsterColors.lightSurfaceContainerLow,
    surfaceContainer: AsterColors.lightSurfaceContainer,
    surfaceContainerHigh: AsterColors.lightSurfaceContainerHigh,
    surfaceContainerHighest: AsterColors.lightSurfaceContainerHighest,
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: AsterColors.darkPrimary,
    onPrimary: AsterColors.darkOnPrimary,
    primaryContainer: AsterColors.darkPrimaryContainer,
    onPrimaryContainer: AsterColors.darkOnPrimaryContainer,
    secondary: AsterColors.darkSecondary,
    onSecondary: AsterColors.darkOnSecondary,
    secondaryContainer: AsterColors.darkSecondaryContainer,
    onSecondaryContainer: AsterColors.darkOnSecondaryContainer,
    tertiary: AsterColors.darkTertiary,
    onTertiary: AsterColors.darkOnTertiary,
    tertiaryContainer: AsterColors.darkTertiaryContainer,
    onTertiaryContainer: AsterColors.darkOnTertiaryContainer,
    error: AsterColors.darkError,
    onError: AsterColors.darkOnError,
    errorContainer: AsterColors.darkErrorContainer,
    onErrorContainer: AsterColors.darkOnErrorContainer,
    surface: AsterColors.darkSurface,
    onSurface: AsterColors.darkOnSurface,
    onSurfaceVariant: AsterColors.darkOnSurfaceVariant,
    outline: AsterColors.darkOutline,
    outlineVariant: AsterColors.darkOutlineVariant,
    shadow: Color(0xFF000000),
    inverseSurface: AsterColors.darkOnSurface,
    onInverseSurface: AsterColors.darkBackground,
    inversePrimary: AsterColors.lightPrimary,
    surfaceTint: AsterColors.darkPrimary,
    surfaceDim: AsterColors.darkBackground,
    surfaceBright: AsterColors.darkSurfaceContainerHighest,
    surfaceContainerLowest: Color(0xFF0C0E13),
    surfaceContainerLow: AsterColors.darkSurfaceContainerLow,
    surfaceContainer: AsterColors.darkSurfaceContainer,
    surfaceContainerHigh: AsterColors.darkSurfaceContainerHigh,
    surfaceContainerHighest: AsterColors.darkSurfaceContainerHighest,
  );
}
